### ISSUE TITLE
Multiple rate in genie scripts for multiple population models

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#243]
Currently, genie scripts use a single rate, we have to introduce multiple rates for mixture models.

**Comment by Qazalbash** [comment]
We implemented the methods to generate data from multi-rate models in 775d1ec95103692c35790eeae9b3d3b100a42993.

**Comment by zeeshan5885** [comment]
I checked multi-rate generation and it is working as expected.
