### ISSUE TITLE
`sage_n_pls_m_gs` giving zero local acceptance rate

### ISSUE THREAD

**Issue by zeeshan5885** [gwkokab/gwkokab#263]
### Check for existing issues

- [X] Completed

### Description

I am using the following script to analyze a power law without Gaussian.

```
sage_n_pls_m_gs \
        --n-pl 1 \
        --n-g 0 \
        --vt-path "../../vts/vt_1_200_ecc_matters.eqx" \
        --posterior-regex "../genie/data/realization_1/posteriors/*.dat" \
        --prior-json ./prior.json \
        --flowMC-json ./flowMC.json \
        --posterior-columns mass_1_source mass_2_source \
        --analysis-time 50 \
        --no-spin \
        --no-tilt
```

All other plots look reasonable except the local acceptance rate.

![local_accs](https://github.com/user-attachments/assets/76b0ff4a-3807-40a9-912e-8280cfbd804c)

The strange thing for me is that I am seeing normal behavior for mixed models, and zero local rate for power law.

**Comment by zeeshan5885** [comment]
Here is the global acceptance rate which looks normal.
![global_accs](https://github.com/user-attachments/assets/7a1e0e30-b47e-4310-b37f-7254d33f6abb)

Even the chains seem to going in the right direction.
![train_chains](https://github.com/user-attachments/assets/725a1e1e-8585-4988-8e99-8058ee0c66f8)

**Comment by Qazalbash** [comment]
We could recover and estimate the parameters after running a solo Power Law Primary Mass Ratio implemented in https://github.com/gwkokab/gwkokab/pull/279. The problem now is in either `TransformedDistribution` or the `MixtureGeneral`!

<details><summary>Local Acceptance Rate</summary>
<p>

![image](https://github.com/user-attachments/assets/26f03762-8ae9-4dd3-b71c-59488126795c)

</p>
</details>

<details><summary>Global Acceptance Rate</summary>
<p>

![image](https://github.com/user-attachments/assets/d489cef7-f476-475a-b195-b3151da00ffd)

</p>
</details>

<details><summary>Training Chains</summary>
<p>

![image](https://github.com/user-attachments/assets/c4638862-0519-4c86-ae98-c46f87496c29)

</p>
</details>

**Comment by Qazalbash** [comment]
When `self.mmin==m1` it yields `jnp.nan` values.

https://github.com/gwkokab/gwkokab/blob/d7bf4a743e69bbe3ec459eac22736ff9e8c3e24c/src/gwkokab/models/_models.py#L806-L808
