### ISSUE TITLE
Sage Script for smoothed power laws with peaks 

### ISSUE THREAD

**Issue by zeeshan5885** [gwkokab/gwkokab#327]
We have already implemented `sage_n_pls_m_gs`, which uses a truncated power-law without smoothing at the lower mass end. However, we also need this similar approach to build different models with any number of peaks (Gaussian) along with a power-law with smoothing.

This model is implemented in the LIGO population [paper](https://arxiv.org/pdf/2111.03634) with the name power-law peak  (PP) model. We can call it `sage_n_pls_m_gs_smoothed`. In this way, we can still choose any combination of power-law and Gaussian.

- [ ] Implementation of Smoothed PowerLaw Peak
- [ ] Sage script

**Comment by Qazalbash** [comment]
added in #374
