### ISSUE TITLE
replace `analysis_time` and `scale_factor` with a single attribute

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#360]
It has been observed that `analysis_time` and `scale_factor` multiply with VT. They should be replaced with a single parameter that will represent `analysis_time` time `scale_factor`.

**Comment by Qazalbash** [comment]
@zeeshan5885 any suggestion on the name of the parameter?

**Comment by zeeshan5885** [comment]
analysis_time
