### ISSUE TITLE
Redshift models for Fake PEs generation. 

### ISSUE THREAD

**Issue by zeeshan5885** [gwkokab/gwkokab#53]
### Description

- Read the models given in the [link](https://colmtalbot.github.io/gwpopulation/_autosummary/gwpopulation.models.redshift.html).
- Also read the cited papers.
- Implement those models in GWKokab.
- Generate random numbers from those distributions.
- Store those numbers in our injections files along with (m1_source, m2_source, a1, a2, ecc) as new column name "z".
- Also store them in posterior by using the truncnorm error. However, look into [Amenda's](https://git.ligo.org/amanda.farah/mock-PE/-/tree/main/GWMockCat?ref_type=heads) code for adding fake error in redshift.
- Modify the config file to give freedom to user to choose any redshift model.

**Comment by Qazalbash** [comment]
Added in #135
